version: '3'

services:
  pykamino:
    image: pykamino
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/database:/var/lib/postgresql/data
