[scraper]
    [scraper.database]
    user = "user"
    password = "pwd"
    hostname = "localhost"
    port = "10501"
    db_name = "database"

    [scraper.cache]
    user = "user"
    password = "pwd"
    hostname = "localhost"
    port = "27017"
    db_name = "database"
