[global]
products = [ "BTC-USD" ]

[scraper]
    [scraper.database]
    dbms = "postgres"
    user = "user"
    password = "password"
    hostname = "localhost"
    port = "32768"
    db_name = "database"

